// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Repository;

#nullable disable

namespace ProvaPub.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250819205130_AddRandomNumberTable")]
    partial class AddRandomNumberTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tiffany Hamill"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sam Mertz"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dolores McClure"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Monique Kris"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Beth Wisozk"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Priscilla Brekke"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Marcia Weimann"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gary Kreiger"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Beverly Hansen"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Robin Windler"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Kelvin Bogisich"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Audrey Grady"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Casey Kunde"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Terri Koelpin"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Tabitha Russel"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Patty Pollich"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Chris Glover"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Derrick Hand"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Eula Ruecker"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Barry McLaughlin"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProvaPub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gorgeous Cotton Cheese"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantastic Concrete Chips"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Incredible Soft Salad"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gorgeous Soft Fish"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Unbranded Metal Mouse"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Intelligent Soft Salad"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Unbranded Wooden Soap"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Handmade Wooden Computer"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Intelligent Granite Ball"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Unbranded Steel Fish"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Awesome Wooden Towels"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Fantastic Frozen Chicken"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Gorgeous Wooden Salad"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Fantastic Fresh Mouse"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Fantastic Wooden Chair"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Incredible Fresh Chips"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Generic Granite Hat"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Gorgeous Cotton Mouse"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Handcrafted Fresh Cheese"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Refined Cotton Pizza"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.RandomNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.HasOne("ProvaPub.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
