// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Repository;

#nullable disable

namespace ProvaPub.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Garrett Sporer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Delbert Kuphal"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ramon Lind"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Edith Treutel"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Maria Renner"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Meredith Borer"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Adrienne Jenkins"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Thomas Miller"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Guadalupe Kiehn"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Max Lowe"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Leon Gulgowski"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Sean Keeling"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Irving Predovic"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Daryl Klocko"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Katrina Witting"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Claudia Kuphal"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Diane Volkman"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Jonathon Ledner"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Armando Lang"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Joanna Tillman"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProvaPub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sleek Cotton Keyboard"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantastic Metal Cheese"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sleek Granite Cheese"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fantastic Granite Soap"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sleek Frozen Table"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Awesome Concrete Shoes"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Generic Wooden Mouse"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Intelligent Plastic Chair"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Awesome Frozen Tuna"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Handcrafted Wooden Ball"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Incredible Fresh Gloves"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Sleek Soft Soap"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Awesome Plastic Chips"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Gorgeous Concrete Tuna"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Licensed Concrete Gloves"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Fantastic Frozen Table"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Gorgeous Frozen Ball"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Tasty Frozen Ball"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Refined Wooden Salad"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Small Metal Mouse"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.RandomNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.HasOne("ProvaPub.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
