name: .NET CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Test with coverage
        run: >
          dotnet test tests/ProvaPub.Tests/ProvaPub.Tests.csproj
          --configuration Release
          --no-build
          --logger "trx;LogFileName=test-results.trx"
          /p:CollectCoverage=true
          /p:CoverletOutput=tests/ProvaPub.Tests/TestResults/Coverage/
          /p:CoverletOutputFormat=opencover,lcov,json

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/**/*.trx
            **/TestResults/Coverage/**
